kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
  - yarn
  - yarn run parcel build index.html

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts:
    - nso.iptq.io
    source: ./dist
    target: /var/www/nso
    recursive: true
  secrets: [ rsync_user, rsync_key ]
  when:
    branch: [ master ]
